# Generated by Django 4.0.6 on 2022-09-23 16:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('press_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.uuid4, max_length=36)),
                ('press_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accreditation', to='press_application.pressapplication')),
            ],
        ),
    ]
