version: '3.9'

services:
  db:
    image: postgres:14.0
    container_name: wpt_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 1s
        timeout: 1s
        retries: 5
  backend:
    image: wpt_backend
    container_name: wpt_backend
    volumes:
      - ./backend/backend:/code
    ports:
      - '8000:8000'
    command: bash -c 'python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000'
    depends_on:
      db:
        condition: service_healthy
  frontend:
    image: wpt_frontend
    container_name: wpt_frontend
    volumes:
      - ./frontend/public:/code/public
      - ./frontend/src:/code/src
    ports:
      - '3000:3000'
    command: 'npm start'
    depends_on:
      - backend
